# Generated by Django 4.1.4 on 2022-12-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField()),
                ('attempt_no', models.IntegerField()),
                ('call_no', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('spin', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('attempt_started', models.FloatField()),
                ('if_unreachable', models.IntegerField()),
                ('if_not_answering', models.IntegerField()),
                ('answer_time', models.FloatField()),
                ('amd_time', models.FloatField()),
                ('if_dropped', models.IntegerField()),
                ('wait_before_drop', models.FloatField()),
                ('wait_time', models.FloatField()),
                ('talk_time', models.FloatField()),
                ('clerical_time', models.FloatField()),
            ],
        ),
    ]
