# Generated by Django 4.0.2 on 2023-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalresults',
            name='shift_finished',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='globalresults',
            name='shift_started',
            field=models.IntegerField(null=True),
        ),
    ]
