# Generated by Django 4.0.2 on 2023-01-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_globalresults_shift_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalresults',
            name='shift_finished',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='shift_started',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
