# Generated by Django 4.1.4 on 2022-12-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_globalresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalresults',
            name='amd_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='answer_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='attempt_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='attempt_started',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='call_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='clerical_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='if_dropped',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='if_not_answering',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='if_unreachable',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='run',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='spin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='talk_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='wait_before_drop',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='globalresults',
            name='wait_time',
            field=models.FloatField(null=True),
        ),
    ]
