# Generated by Django 4.0.2 on 2023-01-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_alter_globalresults_amd_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalresults',
            name='queue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='globalresults',
            index=models.Index(fields=['run', 'call_no', 'batch'], name='simulator_g_run_3a5ae5_idx'),
        ),
    ]
